server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: none

spring:
  main:
    lazy-initialization: true
  session:
    jdbc:
      initialize-schema: never

logging:
  level:
    root: WARN
    com.agentsupport: INFO
